### PR TITLE
Ignore non-enumerable properties on validators

### LINKED ISSUE #3: Validator operates on all keys of validator objects, not just enumerable keys
In a production environment when `Array.prototype.includes` is polyfilled and the resulting bundle is loaded in IE11 the `includes` key on an array of validators is considered to be a validator itself and thus `redux-validator` throws an error expecting `includes` to be an object with `msg` and `func` rather than a function.

I expect this can be fixed by adding a check for [`hasOwnProperty()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) here
https://github.com/MaxLi1994/redux-validator/blob/master/src/validator.babel#L44
and here
https://github.com/MaxLi1994/redux-validator/blob/master/src/validator.babel#L56

validator error

### PR DESCRIPTION
**Pull request by effervescentia**
fixes https://github.com/MaxLi1994/redux-validator/issues/3

### CODE REVIEW

**Comment by ymaxli** [comment]
Thanks for the pull request!

**Comment by effervescentia** [comment]
Thank you for your prompt response! 😄

**Comment by effervescentia** [comment]
@MaxLi1994 I know you just merged this in record time 😛  but is there any chance you might be able to make an `npm` release today? I'd be mighty grateful 😄

**Comment by ymaxli** [comment]
@effervescentia Done! the latest version is 0.2.2😁 Thx for your reminder

**Comment by effervescentia** [comment]
ayyyy 😎 you're the best @MaxLi1994 appreciate it!

**Pull request merged**
